spring.application.name=proyectoBackendBaseDatosII

spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.isgnsmynpnzisadkwhtb
spring.datasource.password=SunarpDevEP10,
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.data-source-properties.preferQueryMode=simple

jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000
jwt.refresh.expiration=604800000

server.port=8080
server.servlet.context-path=/api

# Configuracion de email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dalton.vicecityz@gmail.com
spring.mail.password=efld onee yjkx bkxd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
app.mail.from-name=Sistema Spa Natural Beauty
app.frontend.url=http://localhost:4200

logging.level.org.springframework.jdbc.core=DEBUG
logging.level.pe.edu.utp.spa.app=DEBUG
